[package]
name = "rmuxinator"
version = "0.1.0"
authors = ["Peter Doherty <pdoherty@protonmail.com>"]
edition = "2018"

[dependencies]
toml = "0.4"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
