layout = "main-horizontal"
name = "foo"
start_directory = "/home/peter/projects/vim"

[[hooks]]
  name = "pane-focus-in"
  command = "run \"tmux display-message 'Hi from pane-focus-in hook!'\""

[[hooks]]
  name = "pane-focus-in"
  command = "run \"sleep 2 && tmux display-message 'Hi from second pane-focus-in hook!'\""

[[windows]]
  layout = "tiled"
  name = "one"
  start_directory = "/home/peter/projects/default-bleh"

  [[windows.panes]]
  commands = ["echo pane-one"]
  name = "killer"

  [[windows.panes]]
  commands = ["echo pane-two"]
  name = "boots"
  start_directory = "/home/peter/projects/rmuxinator/src"

  [[windows.panes]]
  commands = ["echo pane-three"]
  name = "man"

  [[windows.panes]]
  commands = ["echo hi one", "echo intermediate one", "echo bye one"]

[[windows]]
  name = "two"
  start_directory = "/home/peter/projects/default-bleh"

  [[windows.panes]]
  commands = ["echo pane-one"]
  name = "killer"

  [[windows.panes]]
  commands = ["echo pane-two"]
  name = "boots"
  start_directory = "/home/peter/projects/rmuxinator/src"

  [[windows.panes]]
  commands = ["echo pane-three"]
  name = "man"

  [[windows.panes]]
  commands = ["echo hi one", "echo intermediate one", "echo bye one"]

[[windows]]
  name = "three"

  [[windows.panes]]
  commands = ["echo pane-one"]
  name = "killer"

  [[windows.panes]]
  commands = ["echo pane-two"]
  name = "boots"
  start_directory = "/home/peter/projects/rmuxinator/src"

  [[windows.panes]]
  commands = ["echo pane-three"]
  name = "man"

  [[windows.panes]]
  commands = ["echo hi one", "echo intermediate one", "echo bye one"]
