name = "foo"
root = "~/projects/rmuxinator"
windows = [
   { layout = "Tiled", name = "one", root = "/home/peter/projects/rmuxinator", commands = ["echo hi one", "echo bye one"] },
   { name = "two", root = "/home/peter/projects/rmuxinator", commands = ["echo hi two", "echo bye two"] }
]
